version: 2
jobs:
  build:
    docker:
      - image: swift:4
    steps:
      - checkout
      - run:
          name: Run Tests
          command: swift test
  lint:
    docker:
      - image: lgaches/swiftlint:0.24.2
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
workflows:
  version: 2
  build-test-lint:
    jobs:
      - lint
      - build                      